/**
 * Product Intelligence Sprint — the single source of truth for every
 * analytics event LinguABC emits. This file is intentionally the ONE
 * place a new event gets defined: the properties shape here is what
 * record.ts/client.ts validate against, what the KPI queries in
 * src/lib/analytics/kpis.ts read back out of `properties`, and what
 * docs/analytics-taxonomy.html (generated by hand from this file — see
 * that doc's own note) describes for a non-engineering reader. If this
 * file and the dashboard ever disagree, this file is right.
 *
 * Every event doc comment below states, in order: what it is, why it
 * matters, and which KPI(s) from the Product Intelligence brief it
 * powers. "Not yet instrumented" events are listed at the bottom —
 * defined now so the schema/dashboard don't need to change the day they
 * ship, but with zero real call sites today, and the dashboard says so
 * rather than showing a fabricated zero.
 */

// ---------------------------------------------------------------------------
// Identity & Activation
// ---------------------------------------------------------------------------

/**
 * A new account was created (auth.signUp() succeeded and a real user id
 * exists — independent of whether email confirmation is still pending).
 *
 * Why it matters: this is the D1/D7 retention cohort anchor — "day zero"
 * for every learner. Nothing about retention can be computed without
 * knowing when someone started.
 *
 * KPIs: D1 retention (cohort date), D7 retention (cohort date).
 */
export interface SignupCompletedProperties {
  method: "email";
}

/**
 * One step of the onboarding wizard was completed (Continue tapped).
 *
 * Why it matters: onboarding is the only funnel between "created an
 * account" and "activated learner" — this is what tells you exactly
 * which step loses people, rather than just knowing the overall
 * completion rate.
 *
 * KPIs: supports D1 retention (an incomplete onboarding never reaches a
 * real Day 1) by explaining *why* a cohort's D1 number is low.
 */
export interface OnboardingStepCompletedProperties {
  step: "name" | "level" | "goal" | "daily_time" | "interests" | "ready";
  stepIndex: number;
}

/**
 * The full onboarding wizard finished (AI Plan's "Done" — the learner is
 * about to land on Dashboard for the first time with a real profile).
 *
 * Why it matters: this is "activated," the true denominator for D1/D7
 * retention — measuring retention from signup_completed alone would
 * conflate "never finished onboarding" with "churned after using the
 * product," two very different problems needing different fixes.
 *
 * KPIs: D1 retention (denominator), D7 retention (denominator).
 */
export interface OnboardingCompletedProperties {
  englishLevel: string;
  goal: string;
  dailyTimeMinutes: number;
  interestsCount: number;
}

// ---------------------------------------------------------------------------
// Core Learning Loop
// ---------------------------------------------------------------------------

/**
 * A Learning Session (Player/Reading -> ... -> Quiz -> Summary) began.
 *
 * Why it matters: the denominator for both Lesson Completion and Mission
 * Completion — without knowing how many sessions *started*, a completion
 * count alone can't be turned into a rate, which is the number that
 * actually tells you whether the experience is working.
 *
 * KPIs: Lesson completion (denominator, any slotType), Mission completion
 * (denominator, slotType "mission").
 */
export interface LessonStartedProperties {
  contentId: string;
  contentType: "podcast" | "article";
  /** Whether this is one of today's two guided Daily Mission slots, or a casual Explore pick — the same isMission distinction complete-mission.ts already uses for XP/streak. */
  slotType: "mission" | "casual";
  cefrLevel: string;
}

/**
 * A Learning Session finished (completeMission() ran successfully).
 *
 * Why it matters: the single most important "did real learning happen"
 * event in the product — it's the numerator for lesson/mission
 * completion, a DAU/WAU activity signal, and (via streakAfter) the raw
 * material Streak Recovery Rate is computed from.
 *
 * KPIs: Lesson completion (numerator), Mission completion (numerator,
 * when isMission), DAU, WAU, Streak recovery rate (via streakAfter).
 */
export interface LessonCompletedProperties {
  contentId: string;
  contentType: "podcast" | "article";
  isMission: boolean;
  xpEarned: number;
  quizScore: number;
  quizTotal: number;
  durationMinutes: number;
  /** The learner's streak immediately after this completion — lets the dashboard tell a rebuilt streak apart from a stalled one after a reset, without a separate "recovered" event fired at a fragile, easy-to-miss moment. */
  streakAfter: number;
}

// ---------------------------------------------------------------------------
// Vocabulary / Spaced Repetition
// ---------------------------------------------------------------------------

/** The /review flow opened with at least one word due. KPI: Vocabulary review completion (denominator). */
export interface VocabularyReviewStartedProperties {
  dueWordCount: number;
}

/** The /review flow reached its completion state (every due word answered). KPI: Vocabulary review completion (numerator). */
export interface VocabularyReviewCompletedProperties {
  wordsReviewed: number;
  correctCount: number;
}

// ---------------------------------------------------------------------------
// Streak & Habit
// ---------------------------------------------------------------------------

/**
 * applyStreak() reset an unprotected streak back to 1 (streakStatus === "reset").
 *
 * Why it matters: the exact moment a habit breaks — without logging this,
 * "streak recovery" has no denominator to divide by.
 *
 * KPI: Streak recovery rate (denominator).
 */
export interface StreakResetProperties {
  previousStreak: number;
  longestStreak: number;
}

/** A second, casual completion after today's mission earned a Streak Shield. KPI: supports Streak recovery rate (leading indicator — shields earned vs. later spent). */
export type StreakShieldEarnedProperties = Record<string, never>;

/** A banked Streak Shield covered a missed day instead of a reset. KPI: Streak recovery rate (a shield-covered day is the cleanest possible "recovery," logged at the moment it happens rather than inferred later). */
export interface StreakShieldUsedProperties {
  streakAfter: number;
}

// ---------------------------------------------------------------------------
// Push / Re-engagement
// ---------------------------------------------------------------------------

/** A device opted into Web Push. KPI: supports Push notification CTR (denominator context — the pool of devices that can ever receive one). */
export type PushSubscribedProperties = Record<string, never>;

/** A device opted out of Web Push. KPI: supports Push notification CTR (shrinks the reachable pool — read alongside push_subscribed, not a KPI on its own). */
export type PushUnsubscribedProperties = Record<string, never>;

/**
 * The daily streak-reminder cron successfully delivered a push to one
 * subscription (src/app/api/push/send-streak-reminders).
 *
 * Why it matters: the denominator for CTR — without logging every send,
 * a click count alone is meaningless.
 *
 * KPI: Push notification CTR (denominator).
 */
export interface NotificationSentProperties {
  streakAtSend: number;
}

/**
 * The learner tapped the OS notification (service worker's
 * notificationclick, public/sw.js).
 *
 * Why it matters: the only direct evidence a return visit was actually
 * caused by the notification, not a coincidence of the learner opening
 * the app anyway that day.
 *
 * KPI: Push notification CTR (numerator).
 */
export type NotificationClickedProperties = Record<string, never>;

// ---------------------------------------------------------------------------
// Session / Engagement
// ---------------------------------------------------------------------------

/**
 * A visit to any authenticated screen began (fired once per tab
 * lifetime by SessionTracker, mounted in the (app) layout).
 *
 * Why it matters: DAU/WAU should count "used the product," not just
 * "completed a lesson" — a learner who reads Progress or chats with Tuto
 * without finishing a lesson that day is still active and should count.
 *
 * KPIs: DAU (distinct users with any event, including this one, per day),
 * WAU (same, trailing 7 days), Average session length (paired with
 * session_ended).
 */
export interface SessionStartedProperties {
  entryPath: string;
}

/**
 * The visit ended (page hidden or unloaded — sent via
 * navigator.sendBeacon so it survives tab close).
 *
 * KPI: Average session length (the only direct duration measurement in
 * the whole taxonomy — everything else is a point-in-time event).
 */
export interface SessionEndedProperties {
  durationMs: number;
}

// ---------------------------------------------------------------------------
// Premium — DEFINED, NOT YET INSTRUMENTED.
// There is no premium tier, paywall, or billing system in LinguABC today
// (confirmed: no Stripe/subscription code anywhere, `premium: boolean` on
// ContentItem is an unused content flag, not a gate). These two events
// are specified now so Premium Conversion has a ready-made shape the
// moment a paywall ships, instead of a schema change blocking that
// launch. Until then they have zero real call sites, and the dashboard
// reports this KPI as "Not applicable" rather than a fabricated 0%.
// ---------------------------------------------------------------------------

/** Would fire when a premium-gated moment is shown. KPI (once shipped): Premium conversion (denominator). */
export interface PremiumPaywallViewedProperties {
  trigger: string;
}

/** Would fire when an upgrade completes. KPI (once shipped): Premium conversion (numerator). */
export interface PremiumUpgradeCompletedProperties {
  plan: string;
}

// ---------------------------------------------------------------------------
// The discriminated union every track() call is checked against.
// ---------------------------------------------------------------------------

export type AnalyticsEvent =
  | { name: "signup_completed"; properties: SignupCompletedProperties }
  | { name: "onboarding_step_completed"; properties: OnboardingStepCompletedProperties }
  | { name: "onboarding_completed"; properties: OnboardingCompletedProperties }
  | { name: "lesson_started"; properties: LessonStartedProperties }
  | { name: "lesson_completed"; properties: LessonCompletedProperties }
  | { name: "vocabulary_review_started"; properties: VocabularyReviewStartedProperties }
  | { name: "vocabulary_review_completed"; properties: VocabularyReviewCompletedProperties }
  | { name: "streak_reset"; properties: StreakResetProperties }
  | { name: "streak_shield_earned"; properties: StreakShieldEarnedProperties }
  | { name: "streak_shield_used"; properties: StreakShieldUsedProperties }
  | { name: "push_subscribed"; properties: PushSubscribedProperties }
  | { name: "push_unsubscribed"; properties: PushUnsubscribedProperties }
  | { name: "notification_sent"; properties: NotificationSentProperties }
  | { name: "notification_clicked"; properties: NotificationClickedProperties }
  | { name: "session_started"; properties: SessionStartedProperties }
  | { name: "session_ended"; properties: SessionEndedProperties }
  | { name: "premium_paywall_viewed"; properties: PremiumPaywallViewedProperties }
  | { name: "premium_upgrade_completed"; properties: PremiumUpgradeCompletedProperties };

export type AnalyticsEventName = AnalyticsEvent["name"];

/** Every valid event name — used by the API route's zod schema and by kpis.ts's queries. */
export const ANALYTICS_EVENT_NAMES: AnalyticsEventName[] = [
  "signup_completed",
  "onboarding_step_completed",
  "onboarding_completed",
  "lesson_started",
  "lesson_completed",
  "vocabulary_review_started",
  "vocabulary_review_completed",
  "streak_reset",
  "streak_shield_earned",
  "streak_shield_used",
  "push_subscribed",
  "push_unsubscribed",
  "notification_sent",
  "notification_clicked",
  "session_started",
  "session_ended",
  "premium_paywall_viewed",
  "premium_upgrade_completed",
];
