export interface MiniQuizQuestion {
  id: string;
  focus: "grammar" | "vocabulary";
  question: string;
  options: string[];
  correctIndex: number;
}

/**
 * Sprint UX-2 (Interactive Teaching): local, illustrative practice
 * questions for the "Quiz me" quick-check flourish — not generated by
 * the AI. Real per-conversation quiz generation would need a prompt or
 * tool change, which this frontend-only sprint explicitly excludes; this
 * is a small fixed bank standing in for that.
 */
export const MINI_QUIZ_BANK: MiniQuizQuestion[] = [
  {
    id: "grammar-present-perfect",
    focus: "grammar",
    question: "Which sentence uses the present perfect correctly?",
    options: ["I have saw that movie.", "I have seen that movie.", "I has seen that movie.", "I seen that movie."],
    correctIndex: 1,
  },
  {
    id: "grammar-present-simple",
    focus: "grammar",
    question: "Choose the correct form: \"She ___ to the gym every morning.\"",
    options: ["go", "goes", "going", "gone"],
    correctIndex: 1,
  },
  {
    id: "grammar-passive",
    focus: "grammar",
    question: "Which is a correctly formed passive sentence?",
    options: ["The cake was baked by her.", "The cake baked by her.", "Her baked the cake.", "The cake was bake by her."],
    correctIndex: 0,
  },
  {
    id: "vocabulary-procrastinate",
    focus: "vocabulary",
    question: 'What does "procrastinate" mean?',
    options: ["To finish early", "To delay doing something", "To work quickly", "To forget completely"],
    correctIndex: 1,
  },
  {
    id: "vocabulary-reckon",
    focus: "vocabulary",
    question: 'Which word is closest in meaning to "reckon"?',
    options: ["Doubt", "Ignore", "Think", "Forget"],
    correctIndex: 2,
  },
  {
    id: "vocabulary-commute",
    focus: "vocabulary",
    question: '"Commute" most nearly means...',
    options: ["Travel to work", "Take a break", "Cook dinner", "Write a letter"],
    correctIndex: 0,
  },
];

/** `excludeId` keeps a re-roll (clicking "Quiz me" again) from landing on the same question, which would otherwise reuse the same MiniQuiz key and keep its already-revealed answer state. */
export function pickQuizQuestion(focus: "grammar" | "vocabulary" | null, excludeId?: string): MiniQuizQuestion {
  const pool = focus ? MINI_QUIZ_BANK.filter((question) => question.focus === focus) : MINI_QUIZ_BANK;
  const candidates = (pool.length > 0 ? pool : MINI_QUIZ_BANK).filter((question) => question.id !== excludeId);
  const finalPool = candidates.length > 0 ? candidates : MINI_QUIZ_BANK;
  return finalPool[Math.floor(Math.random() * finalPool.length)];
}
